FROM node:18-alpine
WORKDIR /app
COPY backend/package*.json ./backend/
RUN apk add --no-cache bash
COPY backend/ ./backend
WORKDIR /app/backend
RUN npm install --production
EXPOSE 4242
CMD ["node","server.js"]
